modLoader="kotlinfml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/thebrightspark/KSparkLib/issues"

[[mods]]
    modId="ksparklib"
    version="${file.jarVersion}"
    displayName="KSparkLib"
    authors="bright_spark"
    description='''
    A Kotlin library aimed at bringing simple improvements to creating mods in Kotlin
    '''

[[dependencies.ksparklib]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ksparklib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"